### ISSUE TITLE
Saltcheck does not work on Windows Minion

### ISSUE THREAD

**Issue by claudekenni** [wcannon/salt-check#2]
I tried saltcheck on windows and it does not seem to work. Is it even supposed to work?

Result
```
root@salt:/srv/salt/win# salt windows saltcheck.run_state_tests win
windows:
    |_
      ----------
      win:
          ----------
    |_
      ----------
      TEST RESULTS:
          ----------
          Execution Time:
              0.0
          Failed:
              0
          Missing Tests:
              1
          Passed:
              0
          Skipped:
              0
```
Saltcheck File
```yaml
root@salt:/srv/salt/win# cat saltcheck-tests/init.tst
Check if System is correcly licensed:
  module_and_function: license.info
  assertion_section: licensed
  assertion: assertTrue

echo-test-hello:
  module_and_function: test.echo
  args:
    - "hello"
  kwargs:
  assertion: assertEqual
  expected-return:  'hello'
```
