### ISSUE TITLE
Add skip option

### ISSUE THREAD

**Issue by dawidmalina** [wcannon/salt-check#28]
It would be handy to have ability to provide test which for now should be skipped.

something like that:
```
check if {{ file }} exists:
  skip: True
  module_and_function: file.file_exists
  args:
    - {{ file }}
  assertion: assertEqual
  expected-return: True
```
or even

```
check if {{ file }} exists:
  skip: True
```
