### ISSUE TITLE
assertNotIn has different behavior when matching lists than assertIn

### ISSUE THREAD

**Issue by scub** [wcannon/salt-check#5]
When providing a unicode string for `expected-return`  to the assertion `assertNotIn` the string is converted into a list before the assert is carried out causing unreliable results. 

I opened https://github.com/wcannon/salt-check/pull/4 to impart consistency in behavior between `assertIn` and `assertNotIn`, let me know what you think! 

Example state:
```
remove_user:
  user.absent:
    - name: rawr
    - purge: True
    - force: True
```

Example test:
```
test_user_removed:
  module_and_function: user.list_users
  assertion: assertNotIn
  expected-return: rawr
```
