### ISSUE TITLE
don't know what missing in tests

### ISSUE THREAD

**Issue by squall2751** [wcannon/salt-check#5]
Hi all,

I've run a saltcheck for my script, but it return me 1 Missing Tests and without any information for me to debug what i'm missing or wrong. below is my test script and result.

Can the result give more information, such like which line have problem or other things.

Thanks.

```
user_list_test:
  module_and_function: cmd.run
  args:
    - 'C:\Script\Domain_LocalAdminMembers.vbs "{{ grains['nodename'] }}"'
  kwargs:
  assertion: assertEqual
  expected-return:  True

get_software_list_test:
  module_and_function: cmd.run
  args:
    - 'wmic /output:"C:\Script\{{ grains['nodename']}}-softwarelist.csv" product get name,version /format:csv'
  kwargs:
  assertion: assertEqual
  expected-return:  True

get_dbuserlist_test:
  module_and_function: cmd.run
  args:
    - 'sqlcmd -S {{ grains['nodename'] }} -E -Q "select name,is_disabled from master.sys.server_principals where type not in ('R', 'C')" -o "C:\Script\{{ grains['nodename'] }}-sql.csv" -s ","'
  kwargs:
  assertion: assertEqual
  expected-return:  True

get_userlist_file_test:
  module_and_function: cp.push
  args:
    - 'C:\Script\{{ grains['nodename'] }}.csv'
  kwargs:
  assertion: assertEqual
  expected-return:  True

get_softwarelist_file_test:
  module_and_function: cp.push
  args:
    - 'C:\Script\{{ grains['nodename'] }}-softwarelist.csv'
  kwargs:
  assertion: assertEqual
  expected-return:  True

get_dbuserlist_file_test:
  module_and_function: cp.push
  args:
    - 'C:\Script\{{ grains['nodename'] }}-sql.csv'
  kwargs:
  assertion: assertEqual
  expected-return:  True

```
```
root@raadmin-Virtual-Machine:/srv/salt# salt 'winabc' saltcheck.run_state_tests assesr
winabc:
    |_
      ----------
      assesr:
          ----------
    |_
      ----------
      TEST RESULTS:
          ----------
          Failed:
              0
          Missing Tests:
              1
          Passed:
              0

```
